Add routing name group
RyanThomas31/routingexercise pull request #5
Opened 2022-06-02 07:44 UTC by RyanThomas31

Add routing name group and updating ajax requests

2022-06-02 12:39 UTC, emuroiwaa requested changes

2022-06-02 12:39 UTC, emuroiwaa commented on resources/views/welcome.blade.php
> +                    url: "http://127.0.0.1:8000/api/posts/update/" + id + "?name=" + name + "&post=" + post + "&cell=" + cell,
API url should be an environment variable

2022-06-02 12:39 UTC, emuroiwaa commented on routes/api.php
> +Route::group(['prefix'=>'posts'], function(){
add necessary white spaces

2022-06-02 12:39 UTC, emuroiwaa commented on routes/api.php
> +});
no newline at EOF

2022-06-02 12:39 UTC, emuroiwaa commented on resources/views/welcome.blade.php
> +                var name = post.Name,
ideally variable names and object key should be camel case or  https://www.codementor.io/@veenitchauhan/basics-of-naming-conventions-for-php-developers-eliexmew6

2022-06-07 05:39 UTC, RyanThomas31 commented on resources/views/welcome.blade.php
> +                var name = post.Name,
@emuroiwaa the URL above is talking about PHP variables, in this case on line 180 I'm making use of Javascript variables.

2022-06-07 05:48 UTC, emuroiwa commented on resources/views/welcome.blade.php
> +                var name = post.Name,
Yes correct, do you have something similar for JS

2022-06-07 06:21 UTC, RyanThomas31 commented on resources/views/welcome.blade.php
> +                var name = post.Name,
so, in PHP you get the $variable naming convention which could be camel cased like $postName however in Javascript you declare a variable using var, let, const. I'm changing it to camel casing and adding more detail to describe what the variable is getting. Comitting my changes now

2022-06-07 06:25 UTC, emuroiwaa requested changes

2022-06-07 06:25 UTC, emuroiwaa commented on resources/views/welcome.blade.php
> +                    url: "{{ env('APP_URL')}}/api/posts/create?" + "name=" + userName + "&post=" + postMessage + "&cell=" + postCell,
make spacing constant

2022-06-07 06:25 UTC, emuroiwaa commented on resources/views/welcome.blade.php
> +                    url: "{{ env('APP_URL')}}/api/posts/update/" + id + "?name=" + userName + "&post=" + postMessage + "&cell=" + postCell,
same here

2022-06-07 07:40 UTC, merged